apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: multi-k8s-example-com
spec:
  secretName: multi-k8s-example
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s-example.com
  dnsNames:
    - multi-k8s-example.com
    - www.multi-k8s-example.com
