apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: multi-k8s-com-tls
spec:
  secretName: multi-k8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 34.66.151.192
  dnsNames:
    - 34.66.151.192
    - www.34.66.151.192
